### ISSUE TITLE
Maybe make an Android app with remote access options?

### ISSUE THREAD

**Issue by slycooper724** [fabiofenoglio/lelo-f1-web-sdk#2]
I think your work on both this repository and the python version are amazing, I also really like the UI for the web client. Do you have any plans to develop an Android app with remote access, and how soon would that be if so. I really would like to see someone doing like that with the SDK. I would if I knew enough, but I'm not great at coding. I forked the web client and added the TogetherJS script to your mobile version. It works, but it doesn't recognize other users on mobile, and it needs alot of setup to be fully functional and to sync the data from the end-user using the F1s.
Best regards,
 - Sly

**Comment by fabiofenoglio** [comment]
Hello and thank you for your interest!
Sadly I am no Android programmer so I won't develop a proper android app. However I plan to improve the existing mobile sample in order to add some features, so I will happily consider the implementation of peer-to-peer access via WebRTC or proprietary server.
Please see: https://github.com/fabiofenoglio/lelo-f1-web-sdk/issues/1#issuecomment-623093757

Meanwhile please note that the python client already provides a sample for remote control (but you need a bit of setup at the moment); please see https://github.com/fabiofenoglio/lelo-f1-python-sdk/issues/2#issuecomment-616191046

**Comment by slycooper724** [comment]
Thank you! I did see the socket script you made for the python version. I was going to try and port what you have there to Android studio and refine it and replace the dependencies as I don't think bleak would support android at all. Modifying the existing demo app sounds the easiest as far as a mobile example goes, but don't forget the web version is amazing too. I couldn't seem to get TogetherJS working on the mobile example at all with even it's native chat options, so I don't really know how that would work.
Best regards,
  - Sly

**Comment by fabiofenoglio** [comment]
Hello, I started working on improving that a couple hours ago. Will update ASAP when i'll have something you can test!

**Comment by fabiofenoglio** [comment]
Hello @slycooper724 
since I've got many requests about remote control and similar features, I setup a public hub to share and collaborate on F1 SDK applications.

You can register and start using the BETA version here: https://lelo-hub.fabiofenoglio.it/
Note: since it is based on Web Bluetooth it requires Chrome or Chrome on mobile.

I'd like to ask you if you could kindly open an issue detailing your desiderata (es. remote control, particular control features, interface enhancements, ...) on this other repository: https://github.com/fabiofenoglio/lelo-f1-hub/issues

Thank you for your cooperation!
